# Generated by Django 4.2.4 on 2023-08-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=60, unique=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Activo"), (2, "Inactivo")], default=1
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=10)),
                ("preapproved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
