# Generated by Django 4.2.4 on 2023-08-23 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=60, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "pending"),
                            (2, "active"),
                            (3, "rejected"),
                            (4, "paid"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("maximum_payment_date", models.DateTimeField(blank=True, null=True)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("outstanding", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
